#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define NOTOSANSTHAI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosansthai_12_regular.h",
  "./notosansthai_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANSTHAI_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosansthai_14_regular.h",
  "./notosansthai_14_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANSTHAI_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosansthai_16_regular.h",
  "./notosansthai_16_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANSTHAI_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosansthai_18_regular.h",
  "./notosansthai_18_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_10_regular.h",
  "./ubuntu_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_12_regular.h",
  "./ubuntu_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
