#!/usr/bin/env python3
"""
Build Thai word segmentation dictionaries from a plain word list.

Produces two outputs:
  1. lib/Epub/Epub/ThaiDictCore.h  -- Flash-resident sorted array (top N words)
  2. data/thai_dict_extended.bin   -- SD card binary (remaining words)

SD binary format:
  Header (16 bytes):
    uint32_t magic      = 0x49414854 ('THAI' little-endian)
    uint32_t version    = 1
    uint32_t word_count
    uint32_t block_size (words per coarse-index block)

  Coarse index (ceil(word_count / block_size) entries):
    Each entry:
      uint32_t file_offset   -- byte offset of first word in this block
      uint8_t  key[32]       -- first word of block, zero-padded to 32 bytes

  Word data:
    All words packed as null-terminated UTF-8, sorted lexicographically

Binary search procedure on device:
  1. Binary search coarse index (loaded into static RAM buffer at startup) to
     find the block whose first key <= query < next block's first key.
  2. Seek to block's file_offset, read words sequentially until past the
     target or end of block.
"""

import argparse
import os
import struct
import sys

CORE_COUNT    = 5000
BLOCK_SIZE    = 128       # words per SD coarse-index block
KEY_LEN       = 32        # bytes per coarse-index key (zero-padded)
MAGIC         = 0x49414854  # 'THAI' LE
VERSION       = 1

def is_pure_thai(word: str) -> bool:
    return bool(word) and all(0x0E00 <= ord(c) <= 0x0E7F for c in word)

def load_words(path: str) -> list[str]:
    with open(path, encoding='utf-8') as f:
        return [l.strip() for l in f if l.strip()]

def build_core_header(words: list[str], out_path: str) -> None:
    """Emit a C++ header with a sorted Flash-resident dictionary."""
    # Pack words as null-terminated UTF-8
    packed = bytearray()
    offsets = []
    for w in words:
        offsets.append(len(packed))
        packed.extend(w.encode('utf-8'))
        packed.append(0)

    lines = [
        "// Auto-generated by scripts/build_thai_dict.py -- DO NOT EDIT",
        "// Thai core dictionary: Flash-resident sorted word list.",
        "// Binary search using THAI_DICT_CORE_OFFSETS[].",
        "#pragma once",
        "#include <cstdint>",
        "",
        f"static constexpr uint32_t THAI_DICT_CORE_COUNT = {len(words)}U;",
        "",
        f"static constexpr char THAI_DICT_CORE_DATA[{len(packed)}] = {{",
    ]

    # Emit data bytes in rows of 16
    row = []
    for i, b in enumerate(packed):
        row.append(f"0x{b:02X}")
        if len(row) == 16 or i == len(packed) - 1:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    lines.append("};")
    lines.append("")

    # Offset table — uint32_t since packed can exceed 64KB for large cores
    lines.append(f"static constexpr uint32_t THAI_DICT_CORE_OFFSETS[{len(offsets)}] = {{")
    row = []
    for i, off in enumerate(offsets):
        row.append(str(off))
        if len(row) == 12 or i == len(offsets) - 1:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    lines.append("};")
    lines.append("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"  Core header: {out_path}")
    print(f"    Words:     {len(words)}")
    print(f"    Data size: {len(packed):,} bytes ({len(packed)//1024}KB) in Flash")
    print(f"    Index size:{len(offsets)*4:,} bytes ({len(offsets)*4//1024}KB) in Flash")

def build_sd_binary(words: list[str], out_path: str) -> None:
    """Emit the SD card binary with coarse index for block-based binary search."""
    word_count = len(words)
    num_blocks = (word_count + BLOCK_SIZE - 1) // BLOCK_SIZE

    # Pack word data first to know file offsets
    # Layout: header(16) + coarse_index(num_blocks * (4+KEY_LEN)) + word_data
    header_size = 16
    index_entry_size = 4 + KEY_LEN
    index_size = num_blocks * index_entry_size
    word_data_base = header_size + index_size

    packed = bytearray()
    block_offsets = []   # file offset of each block's first word

    for i, word in enumerate(words):
        if i % BLOCK_SIZE == 0:
            block_offsets.append(word_data_base + len(packed))
        packed.extend(word.encode('utf-8'))
        packed.append(0)

    # Build binary
    buf = bytearray()

    # Header
    buf += struct.pack('<IIII', MAGIC, VERSION, word_count, BLOCK_SIZE)

    # Coarse index
    for block_idx in range(num_blocks):
        word_idx = block_idx * BLOCK_SIZE
        key_bytes = words[word_idx].encode('utf-8')[:KEY_LEN]
        key_padded = key_bytes.ljust(KEY_LEN, b'\x00')
        buf += struct.pack('<I', block_offsets[block_idx])
        buf += key_padded

    # Word data
    buf += packed

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'wb') as f:
        f.write(buf)

    print(f"  SD binary:  {out_path}")
    print(f"    Words:    {word_count:,}")
    print(f"    Blocks:   {num_blocks} (block size {BLOCK_SIZE})")
    print(f"    Index RAM:{num_blocks * index_entry_size:,} bytes ({num_blocks * index_entry_size // 1024}KB) when loaded")
    print(f"    File size:{len(buf):,} bytes ({len(buf)//1024}KB)")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('word_list', help='Path to plain text word list (one word per line)')
    ap.add_argument('stopwords', help='Path to stopwords file (high-priority words for core)')
    ap.add_argument('--core-out',  default='lib/Epub/Epub/ThaiDictCore.h')
    ap.add_argument('--sd-out',    default='data/thai_dict_extended.bin')
    ap.add_argument('--core-count', type=int, default=CORE_COUNT)
    args = ap.parse_args()

    print("Loading word lists...")
    all_words = load_words(args.word_list)
    stop_words = set(load_words(args.stopwords))

    # Filter to pure Thai only
    pure_all  = sorted({w for w in all_words  if is_pure_thai(w)}, key=lambda w: (len(w), w))
    pure_stop = [w for w in sorted(stop_words, key=lambda w: (len(w), w)) if is_pure_thai(w)]

    # Core = stopwords first, then fill by ascending length
    core: list[str] = []
    seen: set[str] = set()
    for w in pure_stop:
        if w not in seen:
            core.append(w)
            seen.add(w)
    for w in pure_all:
        if len(core) >= args.core_count:
            break
        if w not in seen:
            core.append(w)
            seen.add(w)
    core = core[:args.core_count]

    # Extended = everything else, sorted
    core_set = set(core)
    extended = [w for w in pure_all if w not in core_set]

    # Both must be sorted for binary search
    core.sort()
    extended.sort()

    print(f"\nBuilding core Flash dictionary ({len(core)} words)...")
    build_core_header(core, args.core_out)

    print(f"\nBuilding extended SD dictionary ({len(extended)} words)...")
    build_sd_binary(extended, args.sd_out)

    print("\nDone.")

if __name__ == '__main__':
    main()
