#!/usr/bin/env python3
"""Convert assets/logo-vertical-2208x4227.png (or another PNG) to src/images/BootLogo.h.

Output is 1-bit row-major packed: MSB = left pixel, bit 1 = white, 0 = black (matches Logo120.h).
Width is forced to a multiple of 8 for EInkDisplay::drawImage (required on ESP32-C3 / all targets).

By default the source is rotated 90° counter-clockwise (Pillow convention) before resize so the
boot/sleep logo matches the desired on-device orientation; use --rotate 0 for no rotation.
"""
from __future__ import annotations

import argparse
from pathlib import Path

try:
    from PIL import Image
except ImportError as e:
    raise SystemExit("Install Pillow: pip install Pillow") from e

THRESHOLD = 128


def _swap_aspect_for_rotation(rotate_deg: int) -> bool:
    """90° / 270° (CCW) swap width and height; resize must use swapped aspect ratio."""
    r = rotate_deg % 360
    return r == 90 or r == 270


def image_to_c_header(img: Image.Image, array_name: str) -> str:
    img = img.convert("L")
    width, height = img.size
    if width % 8 != 0:
        raise ValueError(f"width {width} must be multiple of 8")
    pixels = list(img.getdata())
    packed: list[int] = []
    for y in range(height):
        for x in range(0, width, 8):
            byte = 0
            for b in range(8):
                v = pixels[y * width + x + b]
                bit = 1 if v >= THRESHOLD else 0
                byte |= bit << (7 - b)
            packed.append(byte)

    c = "#pragma once\n#include <cstdint>\n\n"
    c += f"// Boot / sleep portrait logo — {width}x{height} (1-bit, MSB=left, 1=white 0=black, row-major)\n"
    c += "// Generated by scripts/gen_boot_logo.py — do not edit by hand.\n"
    c += f"static constexpr int BOOT_LOGO_WIDTH = {width};\n"
    c += f"static constexpr int BOOT_LOGO_HEIGHT = {height};\n"
    c += f"static const uint8_t {array_name}[] = {{\n    "
    for i, v in enumerate(packed):
        c += f"0x{v:02X}, "
        if (i + 1) % 16 == 0:
            c += "\n    "
    c = c.rstrip(", \n") + "\n};\n"
    return c


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        default="assets/logo-vertical-2208x4227.png",
        help="Source PNG (portrait)",
    )
    parser.add_argument(
        "--height",
        type=int,
        default=180,
        help="Target height in pixels (width from aspect ratio, snapped to multiple of 8)",
    )
    parser.add_argument(
        "--rotate",
        type=int,
        default=90,
        help="Degrees counter-clockwise before resize (Pillow); 0 disables. Default 90 for boot logo.",
    )
    parser.add_argument(
        "--aspect-w",
        type=int,
        default=2208,
        help="Aspect numerator (width of unrotated source)",
    )
    parser.add_argument(
        "--aspect-h",
        type=int,
        default=4227,
        help="Aspect denominator (height of unrotated source)",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    in_path = root / args.input
    if not in_path.is_file():
        raise SystemExit(f"Missing input: {in_path}")

    im = Image.open(in_path).convert("RGBA")
    bg = Image.new("RGBA", im.size, (255, 255, 255, 255))
    bg.paste(im, mask=im.split()[3])
    im = bg.convert("RGB")
    if args.rotate % 360 != 0:
        im = im.rotate(args.rotate, expand=True, fillcolor=(255, 255, 255))

    h = max(8, args.height)
    aw, ah = args.aspect_w, args.aspect_h
    if _swap_aspect_for_rotation(args.rotate):
        aw, ah = ah, aw
    w = int(round(h * aw / ah))
    w = max(8, (w // 8) * 8)

    im = im.resize((w, h), Image.Resampling.LANCZOS)

    out_path = root / "src" / "images" / "BootLogo.h"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    text = image_to_c_header(im, "BootLogo")
    out_path.write_text(text, encoding="utf-8")
    print(f"Wrote {out_path} ({w}x{h}, {w * h // 8} bytes bitmap)")


if __name__ == "__main__":
    main()
