#!/usr/bin/env python3
"""
Generate a compact Thai word dictionary DAWG for the EPUB line breaker.

The generator downloads the upstream PyThaiNLP Thai word list, keeps only
whitespace-free Thai-script entries, unions it with a small local supplemental
list, then emits a minimized radix DAWG as a C++ header.
"""

from __future__ import annotations

import argparse
import pathlib
import urllib.request


SOURCE_URL = "https://raw.githubusercontent.com/PyThaiNLP/pythainlp/dev/pythainlp/corpus/orst_words_th.txt"
DEFAULT_OUTPUT = pathlib.Path("lib/Epub/Epub/hyphenation/generated/thai_word_dawg.h")
DEFAULT_SUPPLEMENTAL = pathlib.Path("lib/Epub/Epub/hyphenation/thai_supplemental_words.txt")


class TrieNode:
    __slots__ = ("children", "terminal")

    def __init__(self) -> None:
        self.children: dict[int, TrieNode] = {}
        self.terminal = False


class RadixNode:
    __slots__ = ("edges", "terminal")

    def __init__(self) -> None:
        self.edges: list[tuple[tuple[int, ...], RadixNode]] = []
        self.terminal = False


def is_pure_thai_word(word: str) -> bool:
    if not word or any(ch.isspace() for ch in word):
        return False
    return all(0x0E00 <= ord(ch) <= 0x0E7F for ch in word)


def load_words(source_url: str, supplemental_path: pathlib.Path) -> list[str]:
    with urllib.request.urlopen(source_url) as response:
        upstream_words = response.read().decode("utf-8-sig").splitlines()

    words = {word for word in upstream_words if is_pure_thai_word(word)}

    if supplemental_path.exists():
        for line in supplemental_path.read_text(encoding="utf-8").splitlines():
            word = line.strip()
            if is_pure_thai_word(word):
                words.add(word)

    return sorted(words)


def build_trie(words: list[str]) -> TrieNode:
    root = TrieNode()
    for word in words:
        node = root
        for ch in word:
            symbol = ord(ch) - 0x0E00
            node = node.children.setdefault(symbol, TrieNode())
        node.terminal = True
    return root


def compress_trie(node: TrieNode) -> RadixNode:
    radix_node = RadixNode()
    radix_node.terminal = node.terminal

    for symbol, child in sorted(node.children.items()):
        label = [symbol]
        current = child
        while len(current.children) == 1 and not current.terminal:
            next_symbol, next_child = next(iter(current.children.items()))
            label.append(next_symbol)
            current = next_child
        radix_node.edges.append((tuple(label), compress_trie(current)))

    return radix_node


def minimize_dawg(root: RadixNode) -> tuple[int, list[tuple[bool, tuple[tuple[tuple[int, ...], int], ...]]]]:
    memo: dict[tuple[bool, tuple[tuple[tuple[int, ...], int], ...]], int] = {}
    nodes: list[tuple[bool, tuple[tuple[tuple[int, ...], int], ...]]] = []

    def intern(node: RadixNode) -> int:
        interned_edges = tuple((label, intern(child)) for label, child in node.edges)
        key = (node.terminal, interned_edges)
        existing = memo.get(key)
        if existing is not None:
            return existing
        node_id = len(nodes)
        nodes.append(key)
        memo[key] = node_id
        return node_id

    root_id = intern(root)
    return root_id, nodes


def chunked(values: list[str], size: int) -> str:
    return "\n".join("  " + ", ".join(values[idx : idx + size]) + "," for idx in range(0, len(values), size))


def emit_header(words: list[str], root_id: int, nodes: list[tuple[bool, tuple[tuple[tuple[int, ...], int], ...]]]) -> str:
    label_data: list[int] = []
    edges: list[tuple[int, int, int]] = []
    node_first_edge: list[int] = []
    node_edge_count: list[int] = []
    terminal_bits = [0] * ((len(nodes) + 7) // 8)

    for node_index, (terminal, node_edges) in enumerate(nodes):
        node_first_edge.append(len(edges))
        node_edge_count.append(len(node_edges))
        if terminal:
            terminal_bits[node_index // 8] |= 1 << (node_index % 8)

        for label, child_index in node_edges:
            label_offset = len(label_data)
            label_data.extend(label)
            edges.append((label_offset, child_index, len(label)))

    edge_entries = [f"{{{offset}u, {child}u, {length}u, 0u}}" for offset, child, length in edges]

    return (
        "#pragma once\n\n"
        "#include <cstdint>\n\n"
        "// Auto-generated by scripts/generate_thai_word_dawg.py. Do not edit manually.\n"
        f"// Source dictionary: {SOURCE_URL}\n"
        f"// Retained Thai words: {len(words)}\n\n"
        "namespace thai_word_dawg {\n\n"
        "struct Edge {\n"
        "  uint32_t labelOffset;\n"
        "  uint16_t childIndex;\n"
        "  uint8_t labelLength;\n"
        "  uint8_t reserved;\n"
        "};\n\n"
        f"inline constexpr uint16_t kRootNode = {root_id}u;\n\n"
        "inline constexpr uint8_t kLabelData[] = {\n"
        f"{chunked([f'0x{value:02X}' for value in label_data], 16)}\n"
        "};\n\n"
        "inline constexpr uint32_t kNodeFirstEdge[] = {\n"
        f"{chunked([f'{value}u' for value in node_first_edge], 12)}\n"
        "};\n\n"
        "inline constexpr uint8_t kNodeEdgeCount[] = {\n"
        f"{chunked([f'{value}u' for value in node_edge_count], 24)}\n"
        "};\n\n"
        "inline constexpr uint8_t kNodeTerminalBits[] = {\n"
        f"{chunked([f'0x{value:02X}' for value in terminal_bits], 16)}\n"
        "};\n\n"
        "inline constexpr Edge kEdges[] = {\n"
        f"{chunked(edge_entries, 4)}\n"
        "};\n\n"
        "}  // namespace thai_word_dawg\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the Thai word-break DAWG header")
    parser.add_argument("--source-url", default=SOURCE_URL, help="Upstream word list URL")
    parser.add_argument("--supplemental", type=pathlib.Path, default=DEFAULT_SUPPLEMENTAL,
                        help="Local supplemental Thai word list")
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT, help="Header to generate")
    args = parser.parse_args()

    words = load_words(args.source_url, args.supplemental)
    trie = build_trie(words)
    radix = compress_trie(trie)
    root_id, nodes = minimize_dawg(radix)
    header = emit_header(words, root_id, nodes)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header, encoding="utf-8")


if __name__ == "__main__":
    main()
