// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSANS_14_FONT_ID (-258011273)
#define NOTOSANS_16_FONT_ID (1585207244)
#define NOTOSANS_18_FONT_ID (933549407)
#define NOTOSERIFTHAI_14_FONT_ID (-1069140024)
#define NOTOSERIFTHAI_16_FONT_ID (-1784502803)
#define NOTOSERIFTHAI_18_FONT_ID (-1398268822)
#define UI_10_FONT_ID (-237334231)
#define UI_12_FONT_ID (-1294018523)
#define SMALL_FONT_ID (1279830933)
