// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

// UI fonts (backed by Bai Jamjuree; IDs kept stable for UI rendering)
#define NOTOSANS_18_FONT_ID (-67350552)   // used by EpubReaderMenuActivity font-name display
#define NOTOSANS_36_FONT_ID (-1494688505) // used by EpubReaderMenuActivity font-size display
#define UI_10_FONT_ID (-644519114)
#define UI_12_FONT_ID (-113558108)
#define SMALL_FONT_ID (-1272763354)

// CloudLoop
#define CLOUDLOOP_12_FONT_ID (-1480595138)
#define CLOUDLOOP_14_FONT_ID (-1387328626)
#define CLOUDLOOP_16_FONT_ID (1152739871)
#define CLOUDLOOP_18_FONT_ID (-624511069)
#define CLOUDLOOP_20_FONT_ID (907730542)

// Bookerly
#define BOOKERLY_12_FONT_ID (1100120001)
#define BOOKERLY_14_FONT_ID (1100120002)
#define BOOKERLY_16_FONT_ID (1100120003)
#define BOOKERLY_18_FONT_ID (1100120004)
#define BOOKERLY_20_FONT_ID (1100120005)

// Noto Serif (Bookerly Thai fallback)
#define NOTOSERIF_12_FONT_ID (1100130001)
#define NOTOSERIF_14_FONT_ID (1100130002)
#define NOTOSERIF_16_FONT_ID (1100130003)
#define NOTOSERIF_18_FONT_ID (1100130004)
#define NOTOSERIF_20_FONT_ID (1100130005)

// Bai Jamjuree (reader font family)
#define BAIJAMJUREE_12_FONT_ID (1100140001)
#define BAIJAMJUREE_14_FONT_ID (1100140002)
#define BAIJAMJUREE_16_FONT_ID (1100140003)
#define BAIJAMJUREE_18_FONT_ID (1100140004)
#define BAIJAMJUREE_20_FONT_ID (1100140005)
