// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

// UI fonts (backed by Noto Sans Thai Looped; IDs kept stable for UI rendering)
#define NOTOSANS_18_FONT_ID (-67350552)    // used by EpubReaderMenuActivity font-name display
#define NOTOSANS_36_FONT_ID (-1494688505)  // used by EpubReaderMenuActivity font-size display
#define UI_10_FONT_ID (-644519114)
#define UI_12_FONT_ID (-113558108)
#define SMALL_FONT_ID (-1272763354)

// Bookerly (reader font family)
#define BOOKERLY_12_FONT_ID (1100120001)
#define BOOKERLY_14_FONT_ID (1100120002)
#define BOOKERLY_16_FONT_ID (1100120003)
#define BOOKERLY_18_FONT_ID (1100120004)
#define BOOKERLY_20_FONT_ID (1100120005)

// Noto Sans (reader font family; no 20pt available, FONT_20 clamps to 18pt)
#define NOTOSANS_12_FONT_ID (1100150001)
#define NOTOSANS_14_FONT_ID (1100150002)
#define NOTOSANS_16_FONT_ID (1100150003)
// NOTOSANS_18_FONT_ID already defined above

// Noto Sans Thai Looped (reader font family + Thai fallback for Bookerly and Noto Sans)
#define NOTOSANSTHAILOOPED_12_FONT_ID (1100130001)
#define NOTOSANSTHAILOOPED_14_FONT_ID (1100130002)
#define NOTOSANSTHAILOOPED_16_FONT_ID (1100130003)
#define NOTOSANSTHAILOOPED_18_FONT_ID (1100130004)
#define NOTOSANSTHAILOOPED_20_FONT_ID (1100130005)
